name: Deploy to DigitalOcean App Platform
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - name: Apply spec
        run: |
          doctl apps create --spec do-app-spec.yaml --format ID || \
          doctl apps update $(
            doctl apps list --format ID --no-header | head -n1
          ) --spec do-app-spec.yaml --format ID
